---
workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /pre-build/'
      variables:
        PREBUILD: "true"
    - if: '$CI_COMMIT_MESSAGE =~ /no-build/'
      when: never
    - if: '$CI_COMMIT_TAG != null'
      variables:
        REPO_DIR: "repo"
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        REPO_DIR: "repo-testing"
    - if: $CI_COMMIT_REF_NAME =~ /experimental/
      variables:
        REPO_DIR: "repo-experimental"
    - when: never

variables:
  # used for build docker images
  BUILDER_VERSION: 1.0.2
  # used for build debian based apt
  DEBIAN_BUILDER_VERSION: 1.0.10
  # used for build ubuntu based apt
  UBUNTU_BUILDER_VERSION: 1.0.5
  # used for build centos based yum
  CENTOS_BUILDER_VERSION: 1.0.2
  # used for glager php-fpm7
  ALPINE_PHP_FPM_VERSION: 1.0.1
  KANIKO_VERSION: 1.9.2

stages:
  - pre-build
  - pkg-build
  - docker-build

.kaniko_build: &kaniko_build
  # TO DO. Add image tag check
  # Do not overrive image tag. Imported to follow semver workflow
  # https://gitlab.com/api/v4/projects/11936575/registry/repositories/4037301/tags/
  - /kaniko/executor
    --context "${BUILD_DIR}"
    --build-arg OS=${OS}
    --build-arg OS_VER=${OS_VER}
    --dockerfile "${BUILD_DIR}/Dockerfile"
    --destination "${BUILD_IMG}:${BUILD_TAG}"
    --cache=true
    --cache-repo="${CACHE_REPO}"
    --cleanup

.add_ssh_key: &add_ssh_key
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY_BASE64}" | base64 -d | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo 'Host *' > ~/.ssh/config
  - echo '  StrictHostKeyChecking no' >> ~/.ssh/config
  - echo '  UserKnownHostsFile /dev/null' >> ~/.ssh/config
  - chmod 400 ~/.ssh/config

.build_docker: &build_docker
  # github api have some api rate limits for non auth users, so,
  # we need to create PACKER_GITHUB_API_TOKEN secret in gitlab
  # https://developer.hashicorp.com/packer/docs/configure#packer_github_api_token
  # https://github.com/settings/tokens?type=beta (Public Repositories (read-only))
  # this code should work without PACKER_GITHUB_API_TOKEN,
  # but if packer init command failed, you must to set this vaiable in repo secrets
  # - export PACKER_GITHUB_API_TOKEN=${PACKER_GITHUB_API_TOKEN}
  - cd build/appliance/build/docker
  - packer init .
  - packer validate .
  - export DOCKER_PASSWORD=${CI_REGISTRY_PASSWORD}
  - packer build -color=false -timestamp-ui -warn-on-undeclared-var .


.build_go: &build_go
  - export FULL_PROJECT_PATH=$PWD
  - wget --no-verbose "https://golang.org/dl/go1.16.2.linux-amd64.tar.gz"
  - rm -rf /usr/local/go; tar -C /usr/local -xzf go1.16.2.linux-amd64.tar.gz
  - rm ./go1.16.2.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go version

.build_glbmap: &build_glbmap
  - git clone https://gitlab.com/mikler/glbmap.git
  - cd glbmap && cmake . && make -j4
  - mv src/zmap src/glbmap && chmod +s src/glbmap
  - pwd
  - ls -al
  - cd ../..
  - ls -al

.set_glb_version: &set_glb_version
  - export GLABER_VERSION=$(cat include/version.h | grep GLABER_VERSION | tr -dc 0-9.)
  - echo $GLABER_VERSION

.clean_old_dists: &clean_old_dists
  - rm $FULL_PROJECT_PATH/../glaber*.deb || true

.prepare_sources: &prepare_sources
  - *clean_old_dists
  - *set_glb_version
  - ./bootstrap.sh
  - ./configure
  - make dbschema gettext
  - autoreconf -fvi
  - cp -r build/${OS}/${OS_VER}/ debian && cd debian
  - sed -i "1 s/(.*+/(1:$GLABER_VERSION-${CI_COMMIT_SHORT_SHA}+/g" changelog
  - head -n 5 changelog

.prepare_rpm_sources: &prepare_rpm_sources
  - *set_glb_version
  - ./bootstrap.sh
  - ./configure
  - make dbschema gettext
  - autoreconf -fvi
  - cd ..
  - cp -r glaber glaber-$GLABER_VERSION
  - cd glaber-$GLABER_VERSION
  - pwd
  - ls -al
  - rm -rf glbmap
  - git clone https://gitlab.com/mikler/glbmap.git
  - cd glbmap && cmake . && make -j4
  - mv src/zmap ../zmap &&  cd ..
  - rm -rf glbmap
  - mv zmap glbmap && chmod +s ./glbmap && cd ..
  - tar -czvf glaber-$GLABER_VERSION.tar.gz glaber-$GLABER_VERSION
  - cd ${CI_PROJECT_DIR}
  - cp -r build/${OS}/${OS_VER}/* build/centos
  - mv ../glaber-$GLABER_VERSION.tar.gz build/centos/SOURCES/glaber-$GLABER_VERSION.tar.gz
  - sed -i "2 s/Version:.*/Version:\t$GLABER_VERSION/g" build/centos/SPECS/zabbix.spec

.install_common_apt: &install_common_apt
  - apt-get update
  - apt-get --ignore-missing install -y sshpass build-essential cmake libgmp3-dev gengetopt libpcap-dev flex byacc libjson-c-dev pkg-config libunistring-dev dpkg-dev devscripts wget git gcc automake dh-make build-essential autoconf autotools-dev quilt pkg-config libsnmp-dev libpq-dev libsqlite3-dev libcurl4-openssl-dev libldap2-dev libiksemel-dev libopenipmi-dev libssh2-1-dev unixodbc-dev default-jdk libxml2-dev libpcre3-dev libevent-dev curl libssl-dev

.upload_packages: &upload_packages
  - cd $FULL_PROJECT_PATH; cd ..
  - sshpass -p ${SCP_PASS} scp -o StrictHostKeyChecking=no -r glaber*.deb ${SCP_USER}@glaber.io:~/$REPO_DIR/${OS}/${OS_VER}
  - sshpass -p ${SCP_PASS} ssh -T ${SCP_USER}@glaber.io  "reprepro --confdir /etc/reprepro/conf --waitforlock 120 --dbdir /var/reprepro/$REPO_DIR --outdir /var/www/glaber.io/$REPO_DIR/${OS}/ includedeb ${OS_VER}  ~/$REPO_DIR/${OS}/${OS_VER}/*.deb"
  - sshpass -p ${SCP_PASS} ssh -T ${SCP_USER}@glaber.io  "rm ~/$REPO_DIR/${OS}/${OS_VER}/*.deb"

.upload_rpms: &upload_rpms
  - echo "Will upload to '$REPO_DIR' repo"
  - sshpass -p ${SCP_PASS} scp -o StrictHostKeyChecking=no -r /root/rpmbuild/RPMS/* ${SCP_USER}@glaber.io:/var/www/glaber.io/$REPO_DIR/rhel/${OS_VER}/RPMS/
  - sshpass -p ${SCP_PASS} ssh -T ${SCP_USER}@glaber.io  "cd /var/www/glaber.io/$REPO_DIR/rhel/${OS_VER} && createrepo ."

debian-buster:
  stage: pkg-build
  variables:
    OS: debian
    OS_VER: buster
  image: ${CI_REGISTRY_IMAGE}/${OS}-${OS_VER}-builder:${DEBIAN_BUILDER_VERSION}
  script:
    - export FULL_PROJECT_PATH=$PWD
    - *prepare_sources
    - *build_glbmap
    - dpkg-buildpackage -b --no-sign
    - *upload_packages

# astra:
#  stage: pkg-build
#  variables:
#    OS: astra
#    OS_VER: smolensk
#  tags: ["virtbox"]
#  script:
#    - update-ca-certificates
#    - *build_go
#    - *prepare_sources
#    - *build_glbmap
#    - dpkg-buildpackage -b --no-sign
#    - *upload_packages

debian-bullseye:
  stage: pkg-build
  variables:
    OS: debian
    OS_VER: bullseye
  image: ${CI_REGISTRY_IMAGE}/${OS}-${OS_VER}-builder:${DEBIAN_BUILDER_VERSION}
  script:
    - export FULL_PROJECT_PATH=$PWD
    - *prepare_sources
    - *build_glbmap
    - dpkg-buildpackage -b --no-sign
    - *upload_packages

ubuntu-focal:
  stage: pkg-build
  variables:
    OS: ubuntu
    OS_VER: focal
  image: ${CI_REGISTRY_IMAGE}/${OS}-${OS_VER}-builder:${UBUNTU_BUILDER_VERSION}
  script:
    - export FULL_PROJECT_PATH=$PWD
    - *prepare_sources
    - *build_glbmap
    - dpkg-buildpackage -b --no-sign
    - *upload_packages

ubuntu-bionic:
  stage: pkg-build
  variables:
    OS: ubuntu
    OS_VER: bionic
  image: ${CI_REGISTRY_IMAGE}/${OS}-${OS_VER}-builder:${UBUNTU_BUILDER_VERSION}
  script:
    - export FULL_PROJECT_PATH=$PWD
    - *prepare_sources
    - *build_glbmap
    - dpkg-buildpackage -b --no-sign
    - *upload_packages

centos-8:
  stage: pkg-build
  variables:
    OS: almalinux
    OS_VER: 8
  image: ${CI_REGISTRY_IMAGE}/${OS}-${OS_VER}-builder:${CENTOS_BUILDER_VERSION}
  script:
    - export FULL_PROJECT_PATH=$PWD
    - *prepare_rpm_sources
    - cd build/centos
    - yum-builddep -y SPECS/zabbix.spec
    - rpmbuild -bb SPECS/zabbix.spec --define "_sourcedir $PWD/SOURCES" --define "glaber_version $GLABER_VERSION"
    - *upload_rpms

docker-debian-bullseye:
  stage: docker-build
  image: ${CI_REGISTRY_IMAGE}/builder:${BUILDER_VERSION}
  before_script:
    - *add_ssh_key
    - export DOCKER_HOST=ssh://${SSH_USER}@${SERVER}
  script:
    - *set_glb_version
    - *build_docker
    - docker rmi -f $(docker images ${CI_REGISTRY_IMAGE}/glaber-server -q)
    - docker rmi -f $(docker images ${CI_REGISTRY_IMAGE}/glaber-nginx -q)

builder:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: alpine
    OS_VER: "3.17"
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}/docker-cli"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: "${BUILDER_VERSION}"
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'

debian-buster-builder:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: debian
    OS_VER: buster
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: ${DEBIAN_BUILDER_VERSION}
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'

debian-bullseye-builder:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: debian
    OS_VER: bullseye
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: ${DEBIAN_BUILDER_VERSION}
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'

ubuntu-bionic-builder:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: ubuntu
    OS_VER: bionic
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: ${UBUNTU_BUILDER_VERSION}
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'

ubuntu-focal-builder:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: ubuntu
    OS_VER: focal
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: ${UBUNTU_BUILDER_VERSION}
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'

almalinux-8-builder:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: almalinux
    OS_VER: 8
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: ${CENTOS_BUILDER_VERSION}
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'

alpine-php-fpm-7:
  stage: pre-build
  image:
    name: gcr.io/kaniko-project/executor:v${KANIKO_VERSION}-debug
    entrypoint: [""]
  variables:
    OS: alpine
    OS_VER: "3.15"
    BUILD_DIR: "${CI_PROJECT_DIR}/pre-build/${OS}/php-fpm-7"
    BUILD_IMG: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}"
    BUILD_TAG: ${ALPINE_PHP_FPM_VERSION}
    CACHE_REPO: "${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}-cache"
  script:
    - *kaniko_build
  rules:
    - if: '$PREBUILD'
