---
stages:
  - pkg-build

.debug: &debug # testing the build
  - if [ "$CI_JOB_STATUS" == "failed" ]; then
      echo "${TMATE_SSH_PUBKEYS}" >> ~/.ssh/authorized_keys;
      echo "set tmate-authorized-keys ~/.ssh/authorized_keys" > ~/.tmate.conf;
      echo "set tmate-api-key ${TMATE_API_KEY}" >> ~/.tmate.conf;
      echo "set tmate-session-name ${CI_JOB_NAME}" >>  ~/.tmate.conf;
      wget -q https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz;
      tar xvf tmate-2.4.0-static-linux-amd64.tar.xz;
      rm -rf tmate-2.4.0-static-linux-amd64;
      ./tmate -F;
    fi

virtualbox:
  stage: pkg-build
  tags: ["shell"]
  script:
    # - export PACKER_LOG=1
    - cd build/appliance/build/virtualbox/cloud-init
    - bash make-boot-image.sh
    - cd ..
    - packer init .
    - source .env
    - packer validate .
    - packer build -color=false -timestamp-ui -warn-on-undeclared-var .
    - mv vm-output/glaber.qcow2 /opt/vm-output/glaber-int.qcow2
  after_script:
    - *debug

