---
stages:
  - pkg-build

virtualbox:
  stage: pkg-build
  tags: ["shell"]
  script:
    # - export PACKER_LOG=1
    - cd build/appliance/build/virtualbox/cloud-init
    - bash make-boot-image.sh
    - cd ..
    - packer init .
    - source .env
    - packer validate .
    - packer build -color=false -timestamp-ui -warn-on-undeclared-var .
