#!/bin/sh
killall -9 zabbix_server
rm src/zabbix_server/zabbix_server
rm /tmp/zabbix_server_rtc.sock
rm /var/log/zabbix/zabbix_server.log
echo "started" >  /var/log/zabbix/zabbix_server.log
chown zabbix /var/log/zabbix/zabbix_server.log
make
TZ='Asia/Yekaterinburg'; export TZ
src/zabbix_server/zabbix_server -c /etc/zabbix/zabbix_server.conf
tail -f /var/log/zabbix/zabbix_server.log
